global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Security Service
  - job_name: 'security-service'
    static_configs:
      - targets: ['security-service:8001']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Document Processing Service
  - job_name: 'document-processing-service'
    static_configs:
      - targets: ['document-processing-service:8002']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Query Processing Service
  - job_name: 'query-processing-service'
    static_configs:
      - targets: ['query-processing-service:8003']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Web Interface Service
  - job_name: 'web-interface-service'
    static_configs:
      - targets: ['web-interface-service:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # PostgreSQL
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: '/metrics'
    scrape_interval: 60s

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'
    scrape_interval: 60s

  # Nginx
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: '/nginx_status'
    scrape_interval: 30s

  # Node Exporter (if running on host)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['host.docker.internal:9100']
    scrape_interval: 60s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093
